name: tekartik_app_sembast_firestore_type_adapters
description: Sembast Cloud firestore type adapters
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  sembast: ">=3.7.4+3"
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=1.1.2'

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
resolution: workspace
