name: tekartik_app_serialize
description: Simple code generator utility from dart class.
version: 0.1.0
homepage: https://github.com/tekartik/app_common_utils.dart/app_serialize
author: alex <alex@ŧekartik.com>
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  tekartik_app_mirrors:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: dart2
      path: app_mirrors
    version: '>=0.1.1'
  meta:
  dart_style:
  json_annotation:

dev_dependencies:
  dev_test:
  pedantic: ^1.0.0
  test: ^1.0.0
  process_run:


dependency_overrides:
  tekartik_app_mirrors:
    path: ../app_mirrors