name: tekartik_app_serialize
description: Simple code generator utility from dart class.
version: 0.2.0
homepage: https://github.com/tekartik/app_common_utils.dart/app_serialize
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  tekartik_app_mirrors:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_mirrors
    version: '>=0.1.1'
  meta: ">=1.15.0"
  process_run: ">=1.2.2+1"
  dart_style: ">=3.0.0"
  json_annotation:
  path: ">=1.9.0"

dev_dependencies:
  dev_build: ">=1.1.0+2"
  test: ">=1.24.0"
resolution: workspace

