name: tekartik_app_pager
description: Pager helper, assuming a source that can accessed by offset/limit
version: 0.1.4
homepage: https://www.example.com

publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  cv: ">=1.1.0+4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.10.7'
  tekartik_app_emit:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_emit
    version: '>=0.1.3'
  pool: ">=1.5.1"
  quiver:
  dart_style:

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"
resolution: workspace

#  tekartik_common_utils:
#    path: ../../common_utils.dart
