name: tekartik_app_pager
description: Pager helper, assuming a source that can accessed by offset/limit
version: 0.1.4
homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7'
  tekartik_app_emit:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_emit
    version: '>=0.1.3'
  pool:
  quiver:
  dart_style:

dev_dependencies:
  dev_test:
  pedantic: '>=1.4.0'
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:

dependency_overrides:
  tekartik_app_emit:
    path: ../app_emit
#  tekartik_common_utils:
#    path: ../../common_utils.dart