name: tekartik_app_json_schema
description: Json schema definition
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.0+4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
