language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
before_script:
  - pushd repo_support
  - pub get
  - pub run chrome_travis:init
  - source $(pub run chrome_travis:env_rc)
script:
  - dart tool/travis.dart
matrix:
  allow_failures:
    - dart: dev