name: tekartik_app_emit
description: Emit async
version: 0.2.0
homepage: https://www.example.com
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
    version: '>=0.10.7'
  meta:

dev_dependencies:
  pedantic: '>=1.4.0'
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:

#dependency_overrides:
#  tekartik_common_utils:
#    path: ../../common_utils.dart