name: tekartik_app_emit
description: Emit async
version: 0.2.0
homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7'
  meta:

dev_dependencies:
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:

#dependency_overrides:
#  tekartik_common_utils:
#    path: ../../common_utils.dart