name: tekartik_app_bloc
description: Bloc base definition
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  meta: ">=1.15.0"

dev_dependencies:
  dev_build: ">=1.1.0+2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"
