name: tekartik_app_bloc
description: Bloc base definition
version: 0.1.0

environment:
  sdk: '>=2.8.0-dev <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.7'
  meta:

dev_dependencies:
  pedantic:
  test:
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:

