name: tekartik_app_bloc
description: Bloc base definition
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  meta:

dev_dependencies:
  dev_build:
  test:
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:
