name: tekartik_app_web_socket
description: Web socket for flutter app
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_web_socket_io:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_io
      ref: dart3a
    version: '>=0.1.0'
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart3a
    version: '>=0.1.0'
  tekartik_web_socket_browser:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart3a
    version: '>=0.1.0'

dev_dependencies:
  dev_build: ">=1.1.0+1"
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
