name: tekartik_app_web_socket
description: Web socket for flutter app
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  tekartik_web_socket_io:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_io
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_web_socket_browser:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart2_3
    version: '>=0.1.0'

dev_dependencies:
  dev_test:
  process_run:
  test: