name: tekartik_app_rx_bloc
description: Rx Bloc base definition
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_app_bloc:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_bloc
    version: '>=0.2.0'
  rxdart: '>=0.27.7'
  tekartik_app_rx:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_rx
  tekartik_app_common_utils:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"
resolution: workspace

