name: tekartik_app_common_utils
description: App utilities (Pager)
version: 0.1.1
homepage: https://www.example.com
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.8+2'
  pool:
  quiver:
  yaml:
  pub_semver:
  meta:

dev_dependencies:
  pedantic: '>=1.4.0'
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any

#dependency_overrides:
#  tekartik_common_utils:
#    path: ../../common_utils.dart
