name: tekartik_app_common_utils
description: App utilities only dependend on platform, common and lints
version: 0.2.0
homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  pub_semver:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7'
#  tekartik_app_pager:
#    git:
#      url: https://github.com/tekartik/app_common_utils.dart
#      ref: dart2_3
#      path: app_pager
#    version: '>=0.1.3'

dev_dependencies:
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:
  dev_test:

dependency_overrides:
#  tekartik_app_pager:
#    path: ../app_pager
# tmp
#  tekartik_common_utils:
#    path: ../../common_utils.dart