name: tekartik_app_common_utils
description: App utilities only dependend on platform, common and lints
version: 1.0.1
homepage: https://www.example.com

publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  pub_semver: ">=2.1.4"
  yaml:
  cv:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
#  tekartik_app_pager:
#    git:
#      url: https://github.com/tekartik/app_common_utils.dart
#      ref: dart3a
#      path: app_pager
#    version: '>=0.1.3'

dev_dependencies:
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"

dependency_overrides:
resolution: workspace
#  tekartik_app_pager:
#    path: ../app_pager
# tmp
#  tekartik_common_utils:
#    path: ../../common_utils.dart
