name: tekartik_app_text
description: App text helpers (diacritics)
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  collection: ">=1.18.0"
  diacritic: ">=0.1.6"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a


dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
