name: tekartik_app_cv
description: App content values
publish_to: none
version: 0.5.3

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  tekartik_app_common_utils:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app
    version: '>=0.1.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.1.0'
  cv: '>=0.2.9-1'
  meta:
  collection:
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  dev_test:
