name: tekartik_app_sembast_secure
description: Encrypted sembast for secure env.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_sembast
    version: '>=0.1.0'
  sembast: '>=3.7.4'
  path:
  # Dependencies for encryption
  encrypt: '>=5.0.0-0'
  crypto: '>=3.0.0'

dev_dependencies:
  lints:
  test: '>=1.16.0'

dependency_overrides:
  tekartik_app_sembast:
    path: ../app_sembast
  tekartik_app_sqflite:
    path: ../app_sqflite
