name: tekartik_app_sembast_secure
description: Encrypted sembast for secure env.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_sembast
    version: '>=0.1.0'
  sembast:
  path:
  # Dependencies for encryption
  encrypt: '>=5.0.0-0'
  crypto: '>=3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
