name: tekartik_app_sembast_secure
description: Encrypted sembast for secure env.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_sembast
    version: '>=0.1.0'
  sembast: ">=3.7.4+3"
  path: ">=1.9.0"
  # Dependencies for encryption
  encrypt: '>=5.0.0-0'
  crypto: '>=3.0.0'

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace

