name: tekartik_app_crypto
description: Crypto utilities
version: 0.2.4
homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  meta: '>=1.1.6'
  encrypt: '>=5.0.3' # <=5.0.3'
  # Temp aes issue limited to 5.0.1
  # encrypt: '<=5.0.3'
  crypto:
  # Temp web compile issue
  pointycastle: '>=3.2.0-rc0'

dev_dependencies:
  dev_build:
  test: '>=1.5.0'
  # downgrade testing
  file: '>=7.0.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run: '>=0.12.0+1'

_dependency_overrides:
  encrypt:
    git:
      url: https://github.com/leocavalcante/encrypt