name: tekartik_app_crypto
description: Crypto utilities
version: 0.1.1
homepage: https://www.example.com
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.9+1'
  meta: '>=1.1.6'
  encrypt: '>=2.0.0'

dev_dependencies:
  pedantic: '>=1.4.0'
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run:
