name: tekartik_app_crypto
description: Crypto utilities
version: 0.2.3
homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  meta: '>=1.1.6'
  encrypt: '>=3.0.0'
  crypto:
  # Temp web compile issue
  pointycastle: '>=3.2.0-rc0'

dev_dependencies:
  dev_test:
  test: '>=1.5.0'
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
  process_run: '>=0.12.0+1'
