name: tekartik_app_crypto
description: Crypto utilities
version: 0.2.4
homepage: https://www.example.com

publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  meta: ">=1.15.0"
  # encrypt: '>=5.0.3' # <=5.0.3'
  # Temp aes issue limited to 5.0.1
  # encrypt: '<=5.0.3'
  tekartik_encrypt:
    git:
      url: https://github.com/tekartikdev/encrypt
      ref: dart3a
  crypto:
  # Temp web compile issue
  pointycastle: '>=3.2.0-rc0'

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  # downgrade testing
  file: '>=7.0.0'
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"

resolution: workspace
