name: tekartik_app_csv
description: CSV conversion utility
version: 1.3.0
homepage: https://github.com/tekartik/app_common_utils.dart

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  csv: '>=5.0.0-0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
dev_dependencies:
  path:
  dev_build:
  test: ^1.6.0
  process_run:
  build_runner:
  build_test:
