name: tekartik_app_csv
description: CSV conversion utility
version: 1.3.0
homepage: https://github.com/tekartik/app_common_utils.dart

publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  csv: '>=5.0.0-0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
dev_dependencies:
  path: ">=1.9.0"
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
  build_runner: ">=2.4.13"
  build_test:
resolution: workspace
