name: tekartik_app_csv
description: CSV conversion utility
version: 1.0.0
homepage: https://github.com/tekartik/app_common_utils.dart
author: alex <alex@tekartik.com>
deploy_to:
  none

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  csv:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  process_run:
  build_runner:
  build_test:
