name: tekartik_app_csv
description: CSV conversion utility
version: 1.2.0
homepage: https://github.com/tekartik/app_common_utils.dart
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  csv: '>=5.0.0-0'

dev_dependencies:
  pedantic: ^1.8.0
  dev_test:
  test: ^1.6.0
  process_run:
  build_runner:
  build_test: