name: tekartik_app_archive
description: Archive utility
version: 1.3.0
homepage: https://github.com/tekartik/app_common_utils.dart

publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  archive: ">=3.6.1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  path:
  dev_build:
  test: '>=1.6.0'
  process_run:
  build_runner:
  build_test:
