name: tekartik_app_sqflite
description: Sqflite common initialization for dart VM app
version: 0.6.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  sqflite_common_ffi_web: '>=0.4.0'
  sqflite_common_ffi: ">=2.3.4"
  sqflite_common: '>=2.5.4'
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+1"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
