name: tekartik_app_rx
description: Rx helpers
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  rxdart: '>=0.28.0'
  tekartik_app_common_utils:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.15.8'
dev_dependencies:
  dev_build: ">=1.1.0+2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"

dependency_overrides:
  tekartik_app_bloc:
    path: ../app_bloc
  tekartik_app_common_utils:
    path: ../app