name: tekartik_app_http
description: Http for flutter app
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  tekartik_http_browser:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_browser
      ref: dart3a
    version: '>=0.0.1'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.0.1'
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.0.1'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.0.1'
dev_dependencies:
  http:
  dev_build:
  process_run:
  test:
  build_web_compilers: '>=2.4.0'
