name: tekartik_app_mirrors
description: Mirrors tool for code generation on the VM
version: 0.1.1
homepage: https://github.com/tekartik/app_common_utils.dart/app_mirrors
author: alex <alex@ŧekartik.com>

environment:
  sdk: '>=2.7.0-dev <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.7'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  json_annotation:
  process_run:

