name: tekartik_app_mirrors
description: Mirrors tool for code generation on the VM
version: 0.2.0
homepage: https://github.com/tekartik/app_common_utils.dart/app_mirrors
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7'

dev_dependencies:
  dev_test:
  pedantic: ^1.0.0
  test: ^1.0.0
  json_annotation:
  process_run: