name: tekartik_app_mirrors
description: Mirrors tool for code generation on the VM
version: 0.1.0
homepage: https://github.com/tekartik/app_common_utils.dart/app_mirrors
author: alex <alex@ŧekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.8+2'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  json_annotation:
  process_run:
  build_runner: '>=1.2.7'
  build_test: any
  build_web_compilers: any
