name: tekartik_app_cv_sembast
description: Sembast content values helper
version: 0.4.2
publish_to: none
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta:
  cv:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.11.1'
  sembast:
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  dev_test:

dependency_overrides:
  tekartik_app_cv:
    path: ../app_cv