name: tekartik_app_cv_sembast
description: Sembast content values helper
version: 0.5.8
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta:
  cv: '>=0.2.9-1'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
  sembast: '>=3.6.0'
  # sembast:
dev_dependencies:
  test: ^1.14.4
  dev_test:
