name: tekartik_app_cv_sembast
description: Sembast content values helper
version: 1.1.0
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  meta:
  cv: ">=1.1.0+4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
  sembast: ">=3.7.4+3"
  # sembast:
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+1"
