name: app_common_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path:
  process_run: '>=0.10.0'

dev_dependencies:
  test: '>=1.0.0'
  dev_test: '>=0.13.4-dev.1'

dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
