name: app_common_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path:
  process_run: '>=0.10.0'

dev_dependencies:
  test: '>=1.0.0'
  dev_build: '>=0.13.4-dev.1'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

