name: app_common_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=2.10.0-0 <4.0.0'

dependencies:
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.7.8'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  process_run: '>=0.10.0'

dev_dependencies:
  test: '>=1.0.0'
  dev_test: '>=0.13.4-dev.1'

dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart