name: app_common_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.6.0

dependencies:
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  tekartik_ci:
    git:
      url: https://github.com/tekartik/ci.dart
      ref: dart3a
      path: ci

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

