name: tekartik_app_intl
description: locatization common package
version: 0.2.2
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7'
  path:
  fs_shim:
  process_run:
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0