name: tekartik_app_intl
description: locatization common package
version: 0.2.3
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  args: ">=2.6.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  path: ">=1.9.0"
  fs_shim: ">=2.3.3+1"
  process_run: ">=1.2.1+1"
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
