name: tekartik_app_date
description: Date utilities
version: 0.1.6
publish_to: none
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
dev_dependencies:
  lints: ">=5.0.0"
  test: '>=1.24.0'
