name: Run CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: repo_support
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        flutter: [stable, beta, dev]
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: ${{ matrix
      - run: dart --version
      - run: dart pub get
      - run: dart run tool/run_ci.dart