name: tekartik_app_cv_firestore
description: Firestore content values helper
version: 0.4.2
publish_to: none
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta:
  cv:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.11.1'
  tekartik_app_cv:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_cv
    version: '>=0.1.0'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2_3
    version: '>=0.8.9'
  path:
  # Always add for easy test setup
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart2_3
    version: '>=0.8.3'
dev_dependencies:

  pedantic: ^1.9.0
  test: ^1.14.4
  dev_test:

dependency_overrides:
  tekartik_app_cv:
    path: ../app_cv