name: tekartik_app_cv_firestore
description: Firestore content values helper
version: 0.10.9
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta:
  cv: '>=0.2.16+2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.9.0'
  path:
  # Always add for easy test setup
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart3a
    version: '>=0.9.0'
dev_dependencies:
  test: ^1.14.4
  dev_test:

