name: tekartik_app_cv_firestore
description: Firestore content values helper
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.6.0

dependencies:
  meta: ">=1.15.0"
  cv: ">=1.1.0+4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=1.2.1'
  path: ">=1.9.0"
  # Always add for easy test setup
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart3a
    version: '>=0.9.0'
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
resolution: workspace

